### ISSUE TITLE
Unable to use YubiKey 5Ci

### ISSUE THREAD

**Issue by pro-sumer** [joelekstrom/fastmate#90] opened 2022-06-25 15:54 UTC
In Fastmate I can't register my [YubiKey 5Ci](https://www.yubico.com/products/yubikey-5-overview/) as a second factor for Fastmail.

Additionally, if I first add it in a browser, I can't use the key to log in into Fastmail in Fastmate.

Am I doing it wrong or does Fastmate not support (WebAuthn) security keys?

**Comment by joelekstrom** [comment] 2022-06-26 06:45
You’re not doing anything wrong. WebKit/WKWebView does not support OAuth of of the box. Fastmate might be able to work around this by making a separate OAuth session. This would require opening Safari on the login screen and logging in via that before returning to Fastmate. It’s a non-trivial amount of work, and I’ll consider this a feature request that I’ll look into!

**Comment by melvinsalas** [comment] 2022-11-08 17:21
This issue is very old, @pro-sumer do you still have doubts or has the problem been solved?

**Comment by pro-sumer** [comment] 2022-11-08 21:41
> This issue is very old, @pro-sumer do you still have doubts or has the problem been solved?

I'm "waiting" for @joelekstrom to implement this, but he might be waiting for Apple to make this even possible?

WebAuthn support would be so nice, in particular now that Apple implemented Passkeys!

**Comment by pro-sumer** [comment] 2022-11-09 09:13
Also see #44

**Comment by joelekstrom** [comment] 2022-11-09 12:03
I'll close this as a dupe of #44. It's really up to Fastmail. They don't have Webauthn which would be the easiest way for Fastmate to integrate. They do have an OAuth API but it's only for select partners. See the other issue

**Closed by joelekstrom** 2022-11-09 12:03 UTC
